#!/usr/bin/with-contenv bash

function create_key() {
    msg="$1"
    shift
    file="$1"
    shift

    if [[ ! -f "$file" ]]; then
        echo -n $msg
        ssh-keygen -q -f "$file" -N '' "$@"
        echo
        if which restorecon >/dev/null 2>&1; then
            restorecon "$file" "$file.pub"
        fi
        ssh-keygen -l -f "$file.pub"
    fi
}


function create_keys() {
    create_key "Creating SSH2 RSA key; this may take some time ..." \
        /etc/ssh/ssh_host_rsa_key -t rsa
    create_key "Creating SSH2 DSA key; this may take some time ..." \
        /etc/ssh/ssh_host_dsa_key -t dsa
    create_key "Creating SSH2 ECDSA key; this may take some time ..." \
        /etc/ssh/ssh_host_ecdsa_key -t ecdsa
    create_key "Creating SSH2 ED25519 key; this may take some time ..." \
        /etc/ssh/ssh_host_ed25519_key -t ed25519
}

if [[ ! -f "/etc/ssh/.docker-initialized" ]]; then    
    create_keys
    touch "/etc/ssh/.docker-initialized"
fi